### ISSUE TITLE
Facebook icon does not link to their profile

### ISSUE THREAD

**Issue by ianfader** [CCI-Studios/Learninghub#97]
@tgascoigne14 do you have the correct FB link?

**Comment by tgascoigne14** [comment]
It is working for me on all browsers. You must be logged into Facebook to
see their account.

_Tina Gascoigne_
_Account Lead_
CCI Studios, Inc.
_Mail:_ 136 Christina St. N., Sarnia, ON N7T 5T9
_Phone:_ (519) 337-8837
_Fax:_ (519) 337-8316
_Email:_ tgascoigne@ccistudios.com
_Web:_ www.ccistudios.com

**2010, 2012 & 2013 Outstanding Business Achievement Award Recipient**

P _Please print this e-mail only if necessary_

_You have received this email because you have a business relationship with
CCI Studios.  If you believe this was done in error or if you would like to
unsubscribe from any future digital communication, please click here
http://www.ccistudios.com/unsubscribe._
